<?php

define("STRIPE_PUBLIC_KEY_LIVE", $_ENV['STRIPE_PUBLIC_KEY_LIVE']);
define("STRIPE_SECRET_KEY_LIVE", $_ENV['STRIPE_SECRET_KEY_LIVE']);

define("STRIPE_PUBLIC_KEY_TEST", $_ENV['STRIPE_PUBLIC_KEY_TEST']);
define("STRIPE_SECRET_KEY_TEST", $_ENV['STRIPE_SECRET_KEY_TEST']);

define("STRIPE_TEST", false);


define("LIVE_KLIX_BRAND_ID", $_ENV['LIVE_KLIX_BRAND_ID']);
define("LIVE_KLIX_SECRET_KEY", $_ENV['LIVE_KLIX_SECRET_KEY']);

define("TEST_KLIX_BRAND_ID", $_ENV['TEST_KLIX_BRAND_ID']);
define("TEST_KLIX_SECRET_KEY", $_ENV['TEST_KLIX_SECRET_KEY']);

define("KLIX_TEST_MODE", false);


define("REVOLUT_PUBLIC_KEY", $_ENV['REVOLUT_PUBLIC_KEY']);
define("REVOLUT_SECRET_KEY", $_ENV['REVOLUT_SECRET_KEY']);
define("REVOLUT_API_URL", "https://merchant.revolut.com");
define("WEBHOOK_SIGNING_SECRET", $_ENV['WEBHOOK_SIGNING_SECRET']);

$orderStatus = [
    "0" => "Waiting payment",
    "2" => "Paid",
];