<?php

return [
	'admin/index' => [
		'via' => 'GET',
		'pattern' => '/{ln?}/admin',
		'conditions' => ['ln' => '[a-z]{2}'],
		'callable' => ['admin', 'index.php'],
		'type' => 'web',
	],
	'admin/orders' => [
		'via' => 'GET',
		'pattern' => '/{ln?}/admin/orders',
		'conditions' => ['ln' => '[a-z]{2}'],
		'callable' => ['admin', 'orders.php'],
		'type' => 'web',
	],
	'admin/orders_all' => [
		'via' => 'GET',
		'pattern' => '/{ln?}/admin/orders_all',
		'conditions' => ['ln' => '[a-z]{2}'],
		'callable' => ['admin', 'orders_all.php'],
		'type' => 'web',
	],
	'admin/translations' => [
		'via' => 'GET',
		'pattern' => '/{ln?}/admin/translations',
		'conditions' => ['ln' => '[a-z]{2}'],
		'callable' => ['admin', 'translations.php'],
		'type' => 'web',
	],
	'admin/image_import' => [
		'via' => 'GET',
		'pattern' => '/{ln?}/admin/image-import',
		'conditions' => ['ln' => '[a-z]{2}'],
		'callable' => ['admin', 'image_import.php'],
		'type' => 'web',
	],
	'admin/download_invoices' => [
		'via' => 'POST',
		'pattern' => '/{ln?}/admin/download_invoices',
		'conditions' => ['ln' => '[a-z]{2}'],
		'callable' => ['admin', 'download_invoices.php'],
		'type' => 'web',
	],
	'admin/invoices_and_bank_operations' => [
		'via' => 'GET',
		'pattern' => '/{ln?}/admin/invoices_and_bank_operations',
		'conditions' => ['ln' => '[a-z]{2}'],
		'callable' => ['admin', 'invoices_and_bank_operations.php'],
		'type' => 'web',
	],
	'admin/user_list' => [
		'via' => 'GET',
		'pattern' => '/{ln?}/admin/user_list',
		'conditions' => ['ln' => '[a-z]{2}'],
		'callable' => ['admin', 'user_list.php'],
		'type' => 'web',
	],
	'admin/informers' => [
		'via' => 'GET',
		'pattern' => '/{ln?}/admin/informers',
		'conditions' => ['ln' => '[a-z]{2}'],
		'callable' => ['admin', 'informers.php'],
		'type' => 'web',
	],
	'admin/statistics' => [
		'via' => 'GET',
		'pattern' => '/{ln?}/admin/statistics',
		'conditions' => ['ln' => '[a-z]{2}'],
		'callable' => ['admin', 'statistics.php'],
		'type' => 'web',
	],
	'admin/success_payment' => [
		'via' => 'GET',
		'pattern' => '/{ln?}/admin/success-payment/{billId}',
		'conditions' => ['ln' => '[a-z]{2}', 'billId' => '[0-9]+'],
		'callable' => ['admin', 'success_payment.php'],
		'type' => 'web',
	],
	'admin/banners' => [
		'via' => 'GET',
		'pattern' => '/{ln?}/admin/banners',
		'conditions' => ['ln' => '[a-z]{2}'],
		'callable' => ['admin', 'banners.php'],
		'type' => 'web',
	],
	'admin/banner_edit' => [
		'via' => 'GET',
		'pattern' => '/{ln?}/admin/banners/{bannerId}',
		'conditions' => ['ln' => '[a-z]{2}', 'bannerId' => '[0-9]+'],
		'callable' => ['admin', 'banner_edit.php'],
		'type' => 'web',
	],
	'admin/lvp_label' => [
		'via' => 'GET',
		'pattern' => '/{ln?}/admin/lvp_label/{parcel}',
		'conditions' => ['ln' => '[a-z]{2}', 'parcel' => '[a-zA-Z0-9]+'],
		'callable' => ['admin', 'lvp_label.php'],
		'type' => 'web',
	],
	
	//AJAX REQUESTS
	'ajax/admin/load_file_langs' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin/load_file_langs',
		'callable' => ['admin', 'i_load_file_langs'],
		'type' => 'ajax',
    ],
	'ajax/admin/save_lang' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin/save_lang',
		'callable' => ['admin', 'i_save_lang'],
		'type' => 'ajax',
    ],
	'ajax/admin/upload_image_by_sku' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin/upload_image_by_sku',
		'callable' => ['admin', 'i_upload_image_by_sku'],
		'type' => 'ajax',
    ],
	'ajax/admin/upload_image_by_file' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin/upload_image_by_file',
		'callable' => ['admin', 'i_upload_image_by_file'],
		'type' => 'ajax',
    ],
	'ajax/admin/save_bank_data' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin/save_bank_data',
		'callable' => ['admin', 'i_save_bank_data'],
		'type' => 'ajax',
    ],
	'ajax/admin/manual_upload_bank_operation' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin/manual_upload_bank_operation',
		'callable' => ['admin', 'i_manual_upload_bank_operation'],
		'type' => 'ajax',
    ],
	'ajax/admin/load_operations' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin/load_operations',
		'callable' => ['admin', 'i_load_operations'],
		'type' => 'ajax',
    ],
	'ajax/admin/search_bill' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin/search_bill',
		'callable' => ['admin', 'i_search_bill'],
		'type' => 'ajax',
    ],
	'ajax/admin/process_bank_operation' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin/process_bank_operation',
		'callable' => ['admin', 'i_process_bank_operation'],
		'type' => 'ajax',
    ],
	'ajax/admin/add_admin_order_status' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin/add_admin_order_status',
		'callable' => ['admin', 'i_add_admin_order_status'],
		'type' => 'ajax',
    ],
	'ajax/admin/add_omniva_track_number' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin/add_omniva_track_number',
		'callable' => ['admin', 'i_add_omniva_track_number'],
		'type' => 'ajax',
    ],
	'ajax/admin/make_as_legal' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin/make_as_legal',
		'callable' => ['admin', 'i_make_as_legal'],
		'type' => 'ajax',
    ],
	'ajax/admin/change_informer_status' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin/change_informer_status',
		'callable' => ['admin', 'i_change_informer_status'],
		'type' => 'ajax',
    ],
	'ajax/admin/save_informer' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin/save_informer',
		'callable' => ['admin', 'i_save_informer'],
		'type' => 'ajax',
    ],
	'ajax/admin/add_new_informer' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin/add_new_informer',
		'callable' => ['admin', 'i_add_new_informer'],
		'type' => 'ajax',
    ],
	'ajax/admin/get_orders' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin/get_orders',
		'callable' => ['admin', 'i_get_orders'],
		'type' => 'ajax',
    ],
	'ajax/admin/restore_order' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin/restore_order',
		'callable' => ['admin', 'i_restore_order'],
		'type' => 'ajax',
    ],
	'ajax/admin/confirm_order' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin/confirm_order',
		'callable' => ['admin', 'i_confirm_order'],
		'type' => 'ajax',
    ],
	'ajax/admin/create_new_banner' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin/create_new_banner',
		'callable' => ['admin', 'i_create_new_banner'],
		'type' => 'ajax',
    ],
	'ajax/admin/save_banner' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin/save_banner',
		'callable' => ['admin', 'i_save_banner'],
		'type' => 'ajax',
    ],
	'ajax/admin/lvp_create' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin/lvp_create',
		'callable' => ['admin', 'i_lvp_create'],
		'type' => 'ajax',
    ],
	// 'ajax/admin/lvp_label' => [
	// 	'via' => 'POST',
	// 	'pattern' => '/ajax/admin/lvp_label',
	// 	'callable' => ['admin', 'i_lvp_label'],
	// 	'type' => 'ajax',
    // ],
];