<?php

return [
	'admin_products/index' => [
		'via' => 'GET',
		'pattern' => '/{ln?}/admin-products',
		'conditions' => ['ln' => '[a-z]{2}'],
		'callable' => ['admin_products', 'index.php'],
		'type' => 'web',
	],
	'admin_products/attributes' => [
		'via' => 'GET',
		'pattern' => '/{ln?}/admin-products/attributes',
		'conditions' => ['ln' => '[a-z]{2}'],
		'callable' => ['admin_products', 'attributes.php'],
		'type' => 'web',
	],
	'admin_products/attributes_edit' => [
		'via' => 'GET',
		'pattern' => '/{ln?}/admin-products/attributes-edit/{attrId}',
		'conditions' => ['ln' => '[a-z]{2}', 'attrId' => '[0-9]+'],
		'callable' => ['admin_products', 'attributes_edit.php'],
		'type' => 'web',
	],
	'admin_products/excel_product_upload' => [
		'via' => 'POST',
		'pattern' => '/{ln?}/admin-products/excel-product-upload',
		'conditions' => ['ln' => '[a-z]{2}'],
		'callable' => ['admin_products', 'excel_product_upload.php'],
		'type' => 'web',
	],
	'admin_products/edit_category' => [
		'via' => 'GET',
		'pattern' => '/{ln?}/admin-products/edit-category/{categoryId}',
		'conditions' => ['ln' => '[a-z]{2}', 'categoryId' => '[0-9]+'],
		'callable' => ['admin_products', 'edit_category.php'],
		'type' => 'web',
	],
	'admin_products/edit_product' => [
		'via' => 'GET',
		'pattern' => '/{ln?}/admin-products/edit-product/{itemId}',
		'conditions' => ['ln' => '[a-z]{2}', 'itemId' => '[0-9]+'],
		'callable' => ['admin_products', 'edit_product.php'],
		'type' => 'web',
	],
	'admin_products/category_products' => [
		'via' => 'GET',
		'pattern' => '/{ln?}/admin-products/category-products/{categoryId}',
		'conditions' => ['ln' => '[a-z]{2}', 'categoryId' => '[0-9]+'],
		'callable' => ['admin_products', 'category_products.php'],
		'type' => 'web',
	],
	'admin_products/grouped_product_translation' => [
		'via' => 'GET',
		'pattern' => '/{ln?}/admin-products/grouped_product_translation',
		'conditions' => ['ln' => '[a-z]{2}'],
		'callable' => ['admin_products', 'grouped_product_translation.php'],
		'type' => 'web',
	],
	
	//AJAX REQUESTS

	'ajax/admin_products/get_category_list' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/get_category_list',
		'callable' => ['admin_products', 'i_get_category_list'],
		'type' => 'ajax',
    ],
	'ajax/admin_products/get_category_short_info' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/get_category_short_info',
		'callable' => ['admin_products', 'i_get_category_short_info'],
		'type' => 'ajax',
    ],
	'ajax/admin_products/get_category_actions' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/get_category_actions',
		'callable' => ['admin_products', 'i_get_category_actions'],
		'type' => 'ajax',
    ],
	'ajax/admin_products/create_subcategory' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/create_subcategory',
		'callable' => ['admin_products', 'i_create_subcategory'],
		'type' => 'ajax',
    ],
	'ajax/admin_products/get_category_by_lang' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/get_category_by_lang',
		'callable' => ['admin_products', 'i_get_category_by_lang'],
		'type' => 'ajax',
    ],
	'ajax/admin_products/save_category' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/save_category',
		'callable' => ['admin_products', 'i_save_category'],
		'type' => 'ajax',
    ],
	'ajax/admin_products/get_product_by_lang' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/get_product_by_lang',
		'callable' => ['admin_products', 'i_get_product_by_lang'],
		'type' => 'ajax',
    ],
	'ajax/admin_products/save_product' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/save_product',
		'callable' => ['admin_products', 'i_save_product'],
		'type' => 'ajax',
    ],
	'ajax/admin_products/get_similar' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/get_similar',
		'callable' => ['admin_products', 'i_get_similar'],
		'type' => 'ajax',
    ],
	'ajax/admin_products/add_relation' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/add_relation',
		'callable' => ['admin_products', 'i_add_relation'],
		'type' => 'ajax',
    ],
	'ajax/admin_products/delete_relation' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/delete_relation',
		'callable' => ['admin_products', 'i_delete_relation'],
		'type' => 'ajax',
    ],
	'ajax/admin_products/set_flag' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/set_flag',
		'callable' => ['admin_products', 'i_set_flag'],
		'type' => 'ajax',
    ],
	'ajax/admin_products/set_main_image' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/set_main_image',
		'callable' => ['admin_products', 'i_set_main_image'],
		'type' => 'ajax',
    ],
	'ajax/pages/sort_images' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/sort_images',
		'callable' => ['admin_products', 'i_sort_images'],
		'type' => 'ajax',
    ],
	'ajax/pages/upload_product_image' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/upload_product_image',
		'callable' => ['admin_products', 'i_upload_product_image'],
		'type' => 'ajax',
    ],
	'ajax/pages/upload_product_files' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/upload_product_files',
		'callable' => ['admin_products', 'i_upload_product_files'],
		'type' => 'ajax',
    ],
	'ajax/admin_products/delete_image' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/delete_image',
		'callable' => ['admin_products', 'i_delete_image'],
		'type' => 'ajax',
    ],
	'ajax/admin_products/add_new_attribute' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/add_new_attribute',
		'callable' => ['admin_products', 'i_add_new_attribute'],
		'type' => 'ajax',
    ],
	'ajax/admin_products/save_attribute_translation' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/save_attribute_translation',
		'callable' => ['admin_products', 'i_save_attribute_translation'],
		'type' => 'ajax',
    ],
	'ajax/admin_products/add_new_attribute_value' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/add_new_attribute_value',
		'callable' => ['admin_products', 'i_add_new_attribute_value'],
		'type' => 'ajax',
    ],
	'ajax/admin_products/save_attribute_value' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/save_attribute_value',
		'callable' => ['admin_products', 'i_save_attribute_value'],
		'type' => 'ajax',
    ],
	'ajax/admin_products/get_attribute_values' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/get_attribute_values',
		'callable' => ['admin_products', 'i_get_attribute_values'],
		'type' => 'ajax',
    ],
	'ajax/admin_products/add_product_attribute' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/add_product_attribute',
		'callable' => ['admin_products', 'i_add_product_attribute'],
		'type' => 'ajax',
    ],
	'ajax/admin_products/delete_product_attribute' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/delete_product_attribute',
		'callable' => ['admin_products', 'i_delete_product_attribute'],
		'type' => 'ajax',
	],
	'ajax/admin_products/upload_category_image' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/upload_category_image',
		'callable' => ['admin_products', 'i_upload_category_image'],
		'type' => 'ajax',
    ],
	'ajax/admin_products/save_product_categories' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/save_product_categories',
		'callable' => ['admin_products', 'i_save_product_categories'],
		'type' => 'ajax',
    ],
	'ajax/admin_products/delete_category' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/delete_category',
		'callable' => ['admin_products', 'i_delete_category'],
		'type' => 'ajax',
    ],
	'ajax/admin_products/change_category_status' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/change_category_status',
		'callable' => ['admin_products', 'i_change_category_status'],
		'type' => 'ajax',
    ],
	'ajax/admin_products/change_product_status' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/change_product_status',
		'callable' => ['admin_products', 'i_change_product_status'],
		'type' => 'ajax',
    ],
	'ajax/admin_products/add_new_product' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/add_new_product',
		'callable' => ['admin_products', 'i_add_new_product'],
		'type' => 'ajax',
    ],
	'ajax/admin_products/copy_images' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/copy_images',
		'callable' => ['admin_products', 'i_copy_images'],
		'type' => 'ajax',
    ],
	'ajax/admin_products/load_products_for_copy' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/load_products_for_copy',
		'callable' => ['admin_products', 'i_load_products_for_copy'],
		'type' => 'ajax',
    ],
	'ajax/admin_products/change_price' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/change_price',
		'callable' => ['admin_products', 'i_change_price'],
		'type' => 'ajax',
    ],
	'ajax/admin_products/reset_price' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/reset_price',
		'callable' => ['admin_products', 'i_reset_price'],
		'type' => 'ajax',
    ],
	'ajax/admin_products/open_translation' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/open_translation',
		'callable' => ['admin_products', 'i_open_translation'],
		'type' => 'ajax',
    ],
	'ajax/admin_products/save_translation' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/save_translation',
		'callable' => ['admin_products', 'i_save_translation'],
		'type' => 'ajax',
    ],
	'ajax/admin_products/set_max_product_weight' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/set_max_product_weight',
		'callable' => ['admin_products', 'i_set_max_product_weight'],
		'type' => 'ajax',
    ],
	'ajax/admin_products/add_additional_sku' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/add_additional_sku',
		'callable' => ['admin_products', 'i_add_additional_sku'],
		'type' => 'ajax',
    ],
	'ajax/admin_products/remove_additional_sku' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/remove_additional_sku',
		'callable' => ['admin_products', 'i_remove_additional_sku'],
		'type' => 'ajax',
    ],
	'ajax/admin_products/toggle_shippable' => [
		'via' => 'POST',
		'pattern' => '/ajax/admin_products/toggle_shippable',
		'callable' => ['admin_products', 'i_toggle_shippable'],
		'type' => 'ajax',
    ],
];